-- Creación de la base de datos
CREATE DATABASE IF NOT EXISTS prueba_tecnica_jorge CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE prueba_tecnica_jorge;

-- Tabla PRO_PROCESO
CREATE TABLE IF NOT EXISTS PRO_PROCESO (
    PRO_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRO_NOMBRE VARCHAR(100) NOT NULL,
    PRO_PREFIJO VARCHAR(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabla TIP_TIPO_DOC
CREATE TABLE IF NOT EXISTS TIP_TIPO_DOC (
    TIP_ID INT AUTO_INCREMENT PRIMARY KEY,
    TIP_NOMBRE VARCHAR(100) NOT NULL,
    TIP_PREFIJO VARCHAR(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Tabla DOC_DOCUMENTO
CREATE TABLE IF NOT EXISTS DOC_DOCUMENTO (
    DOC_ID INT AUTO_INCREMENT PRIMARY KEY,
    DOC_NOMBRE VARCHAR(255) NOT NULL,
    DOC_CODIGO VARCHAR(50) NOT NULL UNIQUE,
    DOC_CONTENIDO TEXT NOT NULL,
    DOC_ID_TIPO INT NOT NULL,
    DOC_ID_PROCESO INT NOT NULL,
    FOREIGN KEY (DOC_ID_TIPO) REFERENCES TIP_TIPO_DOC(TIP_ID),
    FOREIGN KEY (DOC_ID_PROCESO) REFERENCES PRO_PROCESO(PRO_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
